### ISSUE TITLE
[BUG] On 2 player mode, the piece RNG should be different for both boards.

### ISSUE THREAD

**Issue by xmb9** [adamharmansky/tetr#1]
Example:
[Screenshot of the game](https://media.discordapp.net/attachments/960664404603572234/1016481587220713472/Screenshot_from_2022-09-05_18.53.41.png)

**Comment by adamharmansky** [comment]
No it shouldn't and it's a feature. Many tetris games give both players the same sequence of pieces so that they have the same conditions and can't make excuses. Once I add a custom game feature, the player will be able to disable this.
